@extends('cms.layout')
@section('title',$product->exists ? 'Edit produk' : 'Tambah produk')
@section('content')
<main class="users-page narrow-page"><div class="page-heading"><div><div class="eyebrow"><span class="status-dot"></span> PRODUCT CATALOG</div><h1>{{ $product->exists ? 'Edit produk' : 'Tambah produk' }}</h1><p>Isi nama multibahasa dan detail teknis yang dibutuhkan calon pembeli.</p></div><a class="secondary" href="{{ route('cms.products.index') }}">Kembali</a></div>@if($errors->any())<div class="alert error"><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<section class="user-form-panel"><form class="user-form product-form" method="post" enctype="multipart/form-data" action="{{ $product->exists ? route('cms.products.update',$product) : route('cms.products.store') }}">@csrf @if($product->exists)@method('PUT')@endif
@foreach(['id'=>'Indonesia','en'=>'English','zh'=>'Mandarin'] as $locale=>$label)<label>Nama produk — {{ $label }}</label><input name="name_{{ $locale }}" value="{{ old('name_'.$locale,$product->{'name_'.$locale}) }}" @required($locale==='id')>@endforeach
<div class="form-grid"><div><label>Kategori</label><select name="category" required>@foreach(\App\Models\Product::CATEGORIES as $key=>$label)<option value="{{ $key }}" @selected(old('category',$product->category)===$key)>{{ $label }}</option>@endforeach</select></div><div><label>SKU</label><input name="sku" value="{{ old('sku',$product->sku) }}"></div><div><label>Grade</label><input name="grade" value="{{ old('grade',$product->grade) }}"></div><div><label>Kemasan</label><input name="packaging" value="{{ old('packaging',$product->packaging) }}"></div></div><label>Aplikasi</label><input name="application" value="{{ old('application',$product->application) }}">
@foreach(['id'=>'Indonesia','en'=>'English','zh'=>'Mandarin'] as $locale=>$label)<label>Ringkasan — {{ $label }}</label><textarea name="summary_{{ $locale }}" rows="3">{{ old('summary_'.$locale,$product->{'summary_'.$locale}) }}</textarea>@endforeach
<label>Gambar produk</label><input type="file" name="image" accept="image/jpeg,image/png,image/webp"><div class="form-grid"><div><label>Urutan</label><input type="number" min="0" name="sort_order" value="{{ old('sort_order',$product->sort_order ?? 0) }}" required></div><label class="check-row"><input type="checkbox" name="is_published" value="1" @checked(old('is_published',$product->exists ? $product->is_published : true))> Tampilkan di website</label></div><button class="primary" type="submit"><x-icon name="save"/>Simpan produk</button></form></section></main>
@endsection
